version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo Running tests
      - mkdir results
      - cp src/*.xml results/

reports:
  my-report-name:
    files:
      - "results/*.xml"
    discard-paths: false
